default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432

development:
  <<: *default
  database: "job_development"
  username: "postgres"
  password: "123456789"
  host: "localhost"

production:
  <<: *default
  database: "job_production"
  username: "postgres"
  password: "123456789"
  host: "localhost"

test:
  <<: *default
  database: "job_test"
  username: "postgres"
  password: "123456789"
  host: "localhost"
